package neu.edu.entity;
// Generated Apr 26, 2017 11:58:46 PM by Hibernate Tools 5.2.1.Final

/**
 * Comments generated by hbm2java
 */
public class Comments implements java.io.Serializable {

	private Integer commentsId;
	private Integer comments;
	private int funderFunderId;
	private int projectProjectId;

	public Comments() {
	}

	public Comments(int funderFunderId, int projectProjectId) {
		this.funderFunderId = funderFunderId;
		this.projectProjectId = projectProjectId;
	}

	public Comments(Integer comments, int funderFunderId, int projectProjectId) {
		this.comments = comments;
		this.funderFunderId = funderFunderId;
		this.projectProjectId = projectProjectId;
	}

	public Integer getCommentsId() {
		return this.commentsId;
	}

	public void setCommentsId(Integer commentsId) {
		this.commentsId = commentsId;
	}

	public Integer getComments() {
		return this.comments;
	}

	public void setComments(Integer comments) {
		this.comments = comments;
	}

	public int getFunderFunderId() {
		return this.funderFunderId;
	}

	public void setFunderFunderId(int funderFunderId) {
		this.funderFunderId = funderFunderId;
	}

	public int getProjectProjectId() {
		return this.projectProjectId;
	}

	public void setProjectProjectId(int projectProjectId) {
		this.projectProjectId = projectProjectId;
	}

}
