package neu.edu.entity;
// Generated Apr 26, 2017 11:58:46 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * Creditcard generated by hbm2java
 */
public class Creditcard implements java.io.Serializable {

	private Integer cardId;
	private int cardNumber;
	private int cvv;
	private Date expDate;
	private int funderFunderId;
	private String type;
	private String firstName;
	private String lastName;

	public Creditcard() {
	}

	public Creditcard(int cardNumber, int cvv, int funderFunderId) {
		this.cardNumber = cardNumber;
		this.cvv = cvv;
		this.funderFunderId = funderFunderId;
	}

	public Creditcard(int cardNumber, int cvv, Date expDate, int funderFunderId, String type, String firstName,
			String lastName) {
		this.cardNumber = cardNumber;
		this.cvv = cvv;
		this.expDate = expDate;
		this.funderFunderId = funderFunderId;
		this.type = type;
		this.firstName = firstName;
		this.lastName = lastName;
	}

	public Integer getCardId() {
		return this.cardId;
	}

	public void setCardId(Integer cardId) {
		this.cardId = cardId;
	}

	public int getCardNumber() {
		return this.cardNumber;
	}

	public void setCardNumber(int cardNumber) {
		this.cardNumber = cardNumber;
	}

	public int getCvv() {
		return this.cvv;
	}

	public void setCvv(int cvv) {
		this.cvv = cvv;
	}

	public Date getExpDate() {
		return this.expDate;
	}

	public void setExpDate(Date expDate) {
		this.expDate = expDate;
	}

	public int getFunderFunderId() {
		return this.funderFunderId;
	}

	public void setFunderFunderId(int funderFunderId) {
		this.funderFunderId = funderFunderId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

}
