package neu.edu.entity;
// Generated Apr 26, 2017 11:58:46 PM by Hibernate Tools 5.2.1.Final

/**
 * Funder generated by hbm2java
 */
public class Funder implements java.io.Serializable {

	private Integer funderId;
	private User user;
	private String funderName;

	public Funder() {
	}

	public Funder(User user) {
		this.user = user;
	}

	public Funder(User user, String funderName) {
		this.user = user;
		this.funderName = funderName;
	}

	public Integer getFunderId() {
		return this.funderId;
	}

	public void setFunderId(Integer funderId) {
		this.funderId = funderId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getFunderName() {
		return this.funderName;
	}

	public void setFunderName(String funderName) {
		this.funderName = funderName;
	}

}
