package neu.edu.entity;
// Generated Apr 26, 2017 11:58:46 PM by Hibernate Tools 5.2.1.Final

/**
 * Payement generated by hbm2java
 */
public class Payement implements java.io.Serializable {

	private Integer payementId;
	private int funderFunderId;
	private int projectProjectId;
	private int amount;
	private String city;
	private String name;

	public Payement() {
	}

	public Payement(int funderFunderId, int projectProjectId, int amount) {
		this.funderFunderId = funderFunderId;
		this.projectProjectId = projectProjectId;
		this.amount = amount;
	}

	public Payement(int funderFunderId, int projectProjectId, int amount, String city, String name) {
		this.funderFunderId = funderFunderId;
		this.projectProjectId = projectProjectId;
		this.amount = amount;
		this.city = city;
		this.name = name;
	}

	public Integer getPayementId() {
		return this.payementId;
	}

	public void setPayementId(Integer payementId) {
		this.payementId = payementId;
	}

	public int getFunderFunderId() {
		return this.funderFunderId;
	}

	public void setFunderFunderId(int funderFunderId) {
		this.funderFunderId = funderFunderId;
	}

	public int getProjectProjectId() {
		return this.projectProjectId;
	}

	public void setProjectProjectId(int projectProjectId) {
		this.projectProjectId = projectProjectId;
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
