package neu.edu.entity;
// Generated Apr 26, 2017 11:58:46 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

	private Integer projectId;
	private String projectName;
	private String projectDescription;
	private Integer projectFundingExpectation;
	private Date startDate;
	private Date deadLine;
	private Integer creatorCreatorId;
	private Integer categoryCategoryId;
	private Byte isDeleted;
	private Set<Return> returns = new HashSet<Return>(0);

	public Project() {
	}

	public Project(String projectName, String projectDescription, Integer projectFundingExpectation, Date startDate,
			Date deadLine, Integer creatorCreatorId, Integer categoryCategoryId, Byte isDeleted, Set<Return> returns) {
		this.projectName = projectName;
		this.projectDescription = projectDescription;
		this.projectFundingExpectation = projectFundingExpectation;
		this.startDate = startDate;
		this.deadLine = deadLine;
		this.creatorCreatorId = creatorCreatorId;
		this.categoryCategoryId = categoryCategoryId;
		this.isDeleted = isDeleted;
		this.returns = returns;
	}

	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getProjectDescription() {
		return this.projectDescription;
	}

	public void setProjectDescription(String projectDescription) {
		this.projectDescription = projectDescription;
	}

	public Integer getProjectFundingExpectation() {
		return this.projectFundingExpectation;
	}

	public void setProjectFundingExpectation(Integer projectFundingExpectation) {
		this.projectFundingExpectation = projectFundingExpectation;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getDeadLine() {
		return this.deadLine;
	}

	public void setDeadLine(Date deadLine) {
		this.deadLine = deadLine;
	}

	public Integer getCreatorCreatorId() {
		return this.creatorCreatorId;
	}

	public void setCreatorCreatorId(Integer creatorCreatorId) {
		this.creatorCreatorId = creatorCreatorId;
	}

	public Integer getCategoryCategoryId() {
		return this.categoryCategoryId;
	}

	public void setCategoryCategoryId(Integer categoryCategoryId) {
		this.categoryCategoryId = categoryCategoryId;
	}

	public Byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Set<Return> getReturns() {
		return this.returns;
	}

	public void setReturns(Set<Return> returns) {
		this.returns = returns;
	}

}
