package neu.edu.entity;
// Generated Apr 26, 2017 11:58:46 PM by Hibernate Tools 5.2.1.Final

/**
 * Return generated by hbm2java
 */
public class Return implements java.io.Serializable {

	private Integer returnId;
	private Project project;
	private int from;
	private int to;
	private String gift;

	public Return() {
	}

	public Return(int from, int to) {
		this.from = from;
		this.to = to;
	}

	public Return(Project project, int from, int to, String gift) {
		this.project = project;
		this.from = from;
		this.to = to;
		this.gift = gift;
	}

	public Integer getReturnId() {
		return this.returnId;
	}

	public void setReturnId(Integer returnId) {
		this.returnId = returnId;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public int getFrom() {
		return this.from;
	}

	public void setFrom(int from) {
		this.from = from;
	}

	public int getTo() {
		return this.to;
	}

	public void setTo(int to) {
		this.to = to;
	}

	public String getGift() {
		return this.gift;
	}

	public void setGift(String gift) {
		this.gift = gift;
	}

}
